#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="simulate_demographics.py",
        deps=[
            ctx.path_to(ctx, "IN_DATA", "survival_rates_raw.csv"),
            ctx.path_to(ctx, "IN_MODEL_SPECS", "setup_general.json"),
            ctx.path_to(ctx, "IN_MODEL_SPECS", "transition_constant_tax_rate.json"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_DATA", "fertility_rates.csv"),
            ctx.path_to(ctx, "OUT_DATA", "survival_rates.csv"),
            ctx.path_to(ctx, "OUT_DATA", "mass_distribution.csv"),
        ],
        name="simulate_demographics",
    )
