#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="plot_demographics.py",
        deps=[
            ctx.path_to(ctx, "OUT_DATA", "mass_distribution.csv"),
            ctx.path_to(ctx, "IN_MODEL_SPECS", "setup_general.json"),
        ],
        target=ctx.path_to(ctx, "OUT_FIGURES", "dependency_ratio.png"),
        name="plot_results",
    )
