#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="stationary.py",
        deps=[
            ctx.path_to(ctx, "IN_DATA", "ef.csv"),
            ctx.path_to(ctx, "IN_MODEL_CODE", "solve.py"),
            ctx.path_to(ctx, "IN_MODEL_CODE", "aggregate.py"),
            ctx.path_to(ctx, "IN_MODEL_SPECS", "stationary_initial.json"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_ANALYSIS", "stationary.pickle"),
            ctx.path_to(ctx, "OUT_ANALYSIS", "log", "stationary.log"),
        ],
        name="stationary",
    )
